### ISSUE TITLE
Client side code causing server crash?

### ISSUE THREAD

**Issue by mitchej123** [Technus/TecTech#5]
It looks like [iaeaNuclide](https://github.com/Technus/TecTech/blob/88f7de0d81f1b92862e53d2ae9c2aa6515e80e90/src/main/java/com/github/technus/tectech/elementalMatter/definitions/complex/iaea/iaeaNuclide.java#L32) is calling client.Minecraft and crashing on my local server.

partial stacktrace:
```
[20:52:10] [Server thread/ERROR] [FML]: Fatal errors were detected during the transition from INITIALIZATION to POSTINITIALIZATION. Loading cannot continue
<snip>
UCHE    tectech{3.6.0} [TecTech - Tec Technology!] (TecTech-1.7.10-3.6.0.jar) 
<snip>
[20:52:10] [Server thread/ERROR] [FML]: The following problems were captured during this phase
[20:52:10] [Server thread/ERROR] [FML]: Caught exception from tectech
java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
        at com.github.technus.tectech.elementalMatter.definitions.complex.iaea.iaeaNuclide.run(iaeaNuclide.java:32) ~[iaeaNuclide.class:?]
        at com.github.technus.tectech.loader.ElementalLoader.run(ElementalLoader.java:31) ~[ElementalLoader.class:?]
        at com.github.technus.tectech.loader.MainLoader.load(MainLoader.java:39) ~[MainLoader.class:?]
        at com.github.technus.tectech.TecTech.Load(TecTech.java:82) ~[TecTech.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
```

**Comment by Technus** [comment]
Known resolved.
